apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: carvedrock
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "2.0.0"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: catalog-html
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: carvedrock
spec:
  selector:
    app: catalog-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-html
  namespace: carvedrock
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>CarvedRock Catalog - Black Friday Edition</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background-color: #f0f0f0; }
            h1 { color: #333; }
            .catalog { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .item { margin: 10px 0; padding: 10px; border-left: 4px solid #28a745; }
            .version { position: absolute; top: 10px; right: 10px; color: #666; font-size: 12px; }
            .promo { background: #ff6b6b; color: white; padding: 10px; border-radius: 4px; text-align: center; margin-bottom: 20px; }
        </style>
    </head>
    <body>
        <div class="version">Version: 2.0.0</div>
        <h1>CarvedRock Outdoor Gear Catalog - Black Friday Edition</h1>
        <div class="promo">🎉 BLACK FRIDAY SALE - Up to 50% OFF! 🎉</div>
        <div class="catalog">
            <div class="item">
                <h3>Climbing Gear</h3>
                <p>Professional climbing equipment - <strong>30% OFF</strong></p>
            </div>
            <div class="item">
                <h3>Hiking Equipment</h3>
                <p>Everything for your adventure - <strong>40% OFF</strong></p>
            </div>
            <div class="item">
                <h3>Camping Supplies</h3>
                <p>Quality camping gear - <strong>50% OFF</strong></p>
            </div>
            <div class="item">
                <h3>Winter Collection</h3>
                <p>NEW! Stay warm this season - <strong>25% OFF</strong></p>
            </div>
        </div>
    </body>
    </html>
